//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.UI.SistemaMatricula.ServiceReferenceSchool {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/School.Service.wcf")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alumno", Namespace="http://schemas.datacontract.org/2004/07/School.Entities.Base")]
    [System.SerializableAttribute()]
    public partial class Alumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlumnoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private School.UI.SistemaMatricula.ServiceReferenceSchool.Matricula[] MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private School.UI.SistemaMatricula.ServiceReferenceSchool.Notas[] NotasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlumnoID {
            get {
                return this.AlumnoIDField;
            }
            set {
                if ((this.AlumnoIDField.Equals(value) != true)) {
                    this.AlumnoIDField = value;
                    this.RaisePropertyChanged("AlumnoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Matricula[] Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Notas[] Notas {
            get {
                return this.NotasField;
            }
            set {
                if ((object.ReferenceEquals(this.NotasField, value) != true)) {
                    this.NotasField = value;
                    this.RaisePropertyChanged("Notas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Matricula", Namespace="http://schemas.datacontract.org/2004/07/School.Entities.Base")]
    [System.SerializableAttribute()]
    public partial class Matricula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno AlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlumnoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private School.UI.SistemaMatricula.ServiceReferenceSchool.Grado GradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GradoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatriculoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeccionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno Alumno {
            get {
                return this.AlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.AlumnoField, value) != true)) {
                    this.AlumnoField = value;
                    this.RaisePropertyChanged("Alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlumnoID {
            get {
                return this.AlumnoIDField;
            }
            set {
                if ((this.AlumnoIDField.Equals(value) != true)) {
                    this.AlumnoIDField = value;
                    this.RaisePropertyChanged("AlumnoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Grado Grado {
            get {
                return this.GradoField;
            }
            set {
                if ((object.ReferenceEquals(this.GradoField, value) != true)) {
                    this.GradoField = value;
                    this.RaisePropertyChanged("Grado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GradoID {
            get {
                return this.GradoIDField;
            }
            set {
                if ((this.GradoIDField.Equals(value) != true)) {
                    this.GradoIDField = value;
                    this.RaisePropertyChanged("GradoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatriculoID {
            get {
                return this.MatriculoIDField;
            }
            set {
                if ((this.MatriculoIDField.Equals(value) != true)) {
                    this.MatriculoIDField = value;
                    this.RaisePropertyChanged("MatriculoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeccionID {
            get {
                return this.SeccionIDField;
            }
            set {
                if ((this.SeccionIDField.Equals(value) != true)) {
                    this.SeccionIDField = value;
                    this.RaisePropertyChanged("SeccionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notas", Namespace="http://schemas.datacontract.org/2004/07/School.Entities.Base")]
    [System.SerializableAttribute()]
    public partial class Notas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno AlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlumnoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private School.UI.SistemaMatricula.ServiceReferenceSchool.Curso CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CursoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> NotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NotaIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno Alumno {
            get {
                return this.AlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.AlumnoField, value) != true)) {
                    this.AlumnoField = value;
                    this.RaisePropertyChanged("Alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlumnoID {
            get {
                return this.AlumnoIDField;
            }
            set {
                if ((this.AlumnoIDField.Equals(value) != true)) {
                    this.AlumnoIDField = value;
                    this.RaisePropertyChanged("AlumnoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Curso Curso {
            get {
                return this.CursoField;
            }
            set {
                if ((object.ReferenceEquals(this.CursoField, value) != true)) {
                    this.CursoField = value;
                    this.RaisePropertyChanged("Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CursoID {
            get {
                return this.CursoIDField;
            }
            set {
                if ((this.CursoIDField.Equals(value) != true)) {
                    this.CursoIDField = value;
                    this.RaisePropertyChanged("CursoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Nota {
            get {
                return this.NotaField;
            }
            set {
                if ((this.NotaField.Equals(value) != true)) {
                    this.NotaField = value;
                    this.RaisePropertyChanged("Nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NotaID {
            get {
                return this.NotaIDField;
            }
            set {
                if ((this.NotaIDField.Equals(value) != true)) {
                    this.NotaIDField = value;
                    this.RaisePropertyChanged("NotaID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grado", Namespace="http://schemas.datacontract.org/2004/07/School.Entities.Base")]
    [System.SerializableAttribute()]
    public partial class Grado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private School.UI.SistemaMatricula.ServiceReferenceSchool.Curso[] CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GradoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private School.UI.SistemaMatricula.ServiceReferenceSchool.Matricula[] MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private School.UI.SistemaMatricula.ServiceReferenceSchool.Seccion[] SeccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Curso[] Curso {
            get {
                return this.CursoField;
            }
            set {
                if ((object.ReferenceEquals(this.CursoField, value) != true)) {
                    this.CursoField = value;
                    this.RaisePropertyChanged("Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GradoID {
            get {
                return this.GradoIDField;
            }
            set {
                if ((this.GradoIDField.Equals(value) != true)) {
                    this.GradoIDField = value;
                    this.RaisePropertyChanged("GradoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Matricula[] Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nivel {
            get {
                return this.NivelField;
            }
            set {
                if ((object.ReferenceEquals(this.NivelField, value) != true)) {
                    this.NivelField = value;
                    this.RaisePropertyChanged("Nivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Seccion[] Seccion {
            get {
                return this.SeccionField;
            }
            set {
                if ((object.ReferenceEquals(this.SeccionField, value) != true)) {
                    this.SeccionField = value;
                    this.RaisePropertyChanged("Seccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Curso", Namespace="http://schemas.datacontract.org/2004/07/School.Entities.Base")]
    [System.SerializableAttribute()]
    public partial class Curso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CursoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private School.UI.SistemaMatricula.ServiceReferenceSchool.Grado GradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GradoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private School.UI.SistemaMatricula.ServiceReferenceSchool.Notas[] NotasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CursoID {
            get {
                return this.CursoIDField;
            }
            set {
                if ((this.CursoIDField.Equals(value) != true)) {
                    this.CursoIDField = value;
                    this.RaisePropertyChanged("CursoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Grado Grado {
            get {
                return this.GradoField;
            }
            set {
                if ((object.ReferenceEquals(this.GradoField, value) != true)) {
                    this.GradoField = value;
                    this.RaisePropertyChanged("Grado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GradoID {
            get {
                return this.GradoIDField;
            }
            set {
                if ((this.GradoIDField.Equals(value) != true)) {
                    this.GradoIDField = value;
                    this.RaisePropertyChanged("GradoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Notas[] Notas {
            get {
                return this.NotasField;
            }
            set {
                if ((object.ReferenceEquals(this.NotasField, value) != true)) {
                    this.NotasField = value;
                    this.RaisePropertyChanged("Notas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Seccion", Namespace="http://schemas.datacontract.org/2004/07/School.Entities.Base")]
    [System.SerializableAttribute()]
    public partial class Seccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private School.UI.SistemaMatricula.ServiceReferenceSchool.Grado GradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GradoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeccionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Grado Grado {
            get {
                return this.GradoField;
            }
            set {
                if ((object.ReferenceEquals(this.GradoField, value) != true)) {
                    this.GradoField = value;
                    this.RaisePropertyChanged("Grado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GradoID {
            get {
                return this.GradoIDField;
            }
            set {
                if ((this.GradoIDField.Equals(value) != true)) {
                    this.GradoIDField = value;
                    this.RaisePropertyChanged("GradoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeccionID {
            get {
                return this.SeccionIDField;
            }
            set {
                if ((this.SeccionIDField.Equals(value) != true)) {
                    this.SeccionIDField = value;
                    this.RaisePropertyChanged("SeccionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSchool.IServiceSchool")]
    public interface IServiceSchool {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetData", ReplyAction="http://tempuri.org/IServiceSchool/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetData", ReplyAction="http://tempuri.org/IServiceSchool/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceSchool/GetDataUsingDataContractResponse")]
        School.UI.SistemaMatricula.ServiceReferenceSchool.CompositeType GetDataUsingDataContract(School.UI.SistemaMatricula.ServiceReferenceSchool.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceSchool/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<School.UI.SistemaMatricula.ServiceReferenceSchool.CompositeType> GetDataUsingDataContractAsync(School.UI.SistemaMatricula.ServiceReferenceSchool.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetAlumnosByNombes", ReplyAction="http://tempuri.org/IServiceSchool/GetAlumnosByNombesResponse")]
        School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno[] GetAlumnosByNombes(string alumnoName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetAlumnosByNombes", ReplyAction="http://tempuri.org/IServiceSchool/GetAlumnosByNombesResponse")]
        System.Threading.Tasks.Task<School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno[]> GetAlumnosByNombesAsync(string alumnoName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/AddAlumno", ReplyAction="http://tempuri.org/IServiceSchool/AddAlumnoResponse")]
        bool AddAlumno(School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/AddAlumno", ReplyAction="http://tempuri.org/IServiceSchool/AddAlumnoResponse")]
        System.Threading.Tasks.Task<bool> AddAlumnoAsync(School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetAlumnoById", ReplyAction="http://tempuri.org/IServiceSchool/GetAlumnoByIdResponse")]
        School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno GetAlumnoById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetAlumnoById", ReplyAction="http://tempuri.org/IServiceSchool/GetAlumnoByIdResponse")]
        System.Threading.Tasks.Task<School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno> GetAlumnoByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetAllGrados", ReplyAction="http://tempuri.org/IServiceSchool/GetAllGradosResponse")]
        School.UI.SistemaMatricula.ServiceReferenceSchool.Grado[] GetAllGrados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetAllGrados", ReplyAction="http://tempuri.org/IServiceSchool/GetAllGradosResponse")]
        System.Threading.Tasks.Task<School.UI.SistemaMatricula.ServiceReferenceSchool.Grado[]> GetAllGradosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetAllSecciones", ReplyAction="http://tempuri.org/IServiceSchool/GetAllSeccionesResponse")]
        School.UI.SistemaMatricula.ServiceReferenceSchool.Seccion[] GetAllSecciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetAllSecciones", ReplyAction="http://tempuri.org/IServiceSchool/GetAllSeccionesResponse")]
        System.Threading.Tasks.Task<School.UI.SistemaMatricula.ServiceReferenceSchool.Seccion[]> GetAllSeccionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetIdGrado", ReplyAction="http://tempuri.org/IServiceSchool/GetIdGradoResponse")]
        int GetIdGrado(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetIdGrado", ReplyAction="http://tempuri.org/IServiceSchool/GetIdGradoResponse")]
        System.Threading.Tasks.Task<int> GetIdGradoAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetIdSeccion", ReplyAction="http://tempuri.org/IServiceSchool/GetIdSeccionResponse")]
        int GetIdSeccion(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/GetIdSeccion", ReplyAction="http://tempuri.org/IServiceSchool/GetIdSeccionResponse")]
        System.Threading.Tasks.Task<int> GetIdSeccionAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/AddMatricula", ReplyAction="http://tempuri.org/IServiceSchool/AddMatriculaResponse")]
        bool AddMatricula(School.UI.SistemaMatricula.ServiceReferenceSchool.Matricula matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSchool/AddMatricula", ReplyAction="http://tempuri.org/IServiceSchool/AddMatriculaResponse")]
        System.Threading.Tasks.Task<bool> AddMatriculaAsync(School.UI.SistemaMatricula.ServiceReferenceSchool.Matricula matricula);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSchoolChannel : School.UI.SistemaMatricula.ServiceReferenceSchool.IServiceSchool, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSchoolClient : System.ServiceModel.ClientBase<School.UI.SistemaMatricula.ServiceReferenceSchool.IServiceSchool>, School.UI.SistemaMatricula.ServiceReferenceSchool.IServiceSchool {
        
        public ServiceSchoolClient() {
        }
        
        public ServiceSchoolClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSchoolClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSchoolClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSchoolClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public School.UI.SistemaMatricula.ServiceReferenceSchool.CompositeType GetDataUsingDataContract(School.UI.SistemaMatricula.ServiceReferenceSchool.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<School.UI.SistemaMatricula.ServiceReferenceSchool.CompositeType> GetDataUsingDataContractAsync(School.UI.SistemaMatricula.ServiceReferenceSchool.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno[] GetAlumnosByNombes(string alumnoName) {
            return base.Channel.GetAlumnosByNombes(alumnoName);
        }
        
        public System.Threading.Tasks.Task<School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno[]> GetAlumnosByNombesAsync(string alumnoName) {
            return base.Channel.GetAlumnosByNombesAsync(alumnoName);
        }
        
        public bool AddAlumno(School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno alumno) {
            return base.Channel.AddAlumno(alumno);
        }
        
        public System.Threading.Tasks.Task<bool> AddAlumnoAsync(School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno alumno) {
            return base.Channel.AddAlumnoAsync(alumno);
        }
        
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno GetAlumnoById(int id) {
            return base.Channel.GetAlumnoById(id);
        }
        
        public System.Threading.Tasks.Task<School.UI.SistemaMatricula.ServiceReferenceSchool.Alumno> GetAlumnoByIdAsync(int id) {
            return base.Channel.GetAlumnoByIdAsync(id);
        }
        
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Grado[] GetAllGrados() {
            return base.Channel.GetAllGrados();
        }
        
        public System.Threading.Tasks.Task<School.UI.SistemaMatricula.ServiceReferenceSchool.Grado[]> GetAllGradosAsync() {
            return base.Channel.GetAllGradosAsync();
        }
        
        public School.UI.SistemaMatricula.ServiceReferenceSchool.Seccion[] GetAllSecciones() {
            return base.Channel.GetAllSecciones();
        }
        
        public System.Threading.Tasks.Task<School.UI.SistemaMatricula.ServiceReferenceSchool.Seccion[]> GetAllSeccionesAsync() {
            return base.Channel.GetAllSeccionesAsync();
        }
        
        public int GetIdGrado(string name) {
            return base.Channel.GetIdGrado(name);
        }
        
        public System.Threading.Tasks.Task<int> GetIdGradoAsync(string name) {
            return base.Channel.GetIdGradoAsync(name);
        }
        
        public int GetIdSeccion(string name) {
            return base.Channel.GetIdSeccion(name);
        }
        
        public System.Threading.Tasks.Task<int> GetIdSeccionAsync(string name) {
            return base.Channel.GetIdSeccionAsync(name);
        }
        
        public bool AddMatricula(School.UI.SistemaMatricula.ServiceReferenceSchool.Matricula matricula) {
            return base.Channel.AddMatricula(matricula);
        }
        
        public System.Threading.Tasks.Task<bool> AddMatriculaAsync(School.UI.SistemaMatricula.ServiceReferenceSchool.Matricula matricula) {
            return base.Channel.AddMatriculaAsync(matricula);
        }
    }
}
